# Generated by Django 4.0.4 on 2022-06-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sap',
            new_name='User',
        ),
    ]
